guru:
  jms:
    UserName: seshujms
    Password: seshujmsppwd
    dbUrl: ghijkl
---
spring:
  profiles: de
guru:
  jms:
    UserName: seshujms********
    Password: seshujmsppwd*********
    dbUrl: ghijkl*********
